module.exports = {
  USER: {
    USER_NOT_FOUND: 'USER - USER_NOT_FOUND',
  },
  AUTH: {
    REGISTERED_USER: 'AUTH - REGISTERED_USER',
    NOT_REGISTERED_USER: 'AUTH - NOT_REGISTERED_USER',
    PASSWORD_INCORRECT: 'AUTH - PASSWORD_INCORRECT',
    INVALID_TOKEN: 'AUTH - INVALID_TOKEN',
    JWT_TOKEN_EXPIRED: 'AUTH - JWT_TOKEN_EXPIRED',
  },
  CHATTING: {
    INVALID_MEMBER: 'CHATTING - INVALID_MEMBER',
    INVALID_ROOMKEY: 'CHATTING - INVALID_ROOMKEY',
  },
  COMMON: {
    VALIDATION: 'COMMON - VALIDATION',
    UNKNOWN: 'COMMON - UNKNOWN ERROR!',
    MESSAGE1: 'COMMON - MESSAGE1',
    MESSAGE2: 'COMMON - MESSAGE2',
    MESSAGE3: 'COMMON - MESSAGE3',
  },
  RUNNER: {
    INVALID_STATUS: 'RUNNER - INVALID STATUS',
    REQUEST_NOT_FOUND: 'RUNNER - REQUEST_NOT_FOUND',
    ORDER_NOT_FOUND: 'RUNNER - ORDER_NOT_FOUND',
  },
  SHOPPER: {
    INVALID_STATUS: 'SHOPPER - INVALID STATUS',
    REQUEST_NOT_FOUND: 'SHOPPER - REQUEST_NOT_FOUND',
    ORDER_NOT_FOUND: 'SHOPPER - ORDER_NOT_FOUND',
  },
};
